# .github/workflows/ci-build.yml

name: Build CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
     - '.github/**'
     - 'badges/*'
     - 'pom.xml'
     - '*.svg'     
     - '*.md'     
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - run: npm ci
    
    - run: npm run build --if-present
    
    - run: npm test
